import '../styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import {BasketProvider} from "@/context/BasketContext";
import {UserProvider} from "@/context/UserContext";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="es">
        <body className={inter.className}>
        <UserProvider>
            <BasketProvider>
                {children}
            </BasketProvider>
        </UserProvider>
        </body>
        </html>
    )
}
